# Site settings
title: paul.codes
email: paul.padier@outlook.com
description: #
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://paul.codes" # the base hostname & protocol for your site
twitter_username: paulpadier
github_username:  magni-

# Build settings
markdown: kramdown
highlighter: rouge

# Jekyll
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/page-:num"
