# Site settings
title: paul.codes
email: paul.padier@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  This is Paul Padier's technical blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://paul.codes" # the base hostname & protocol for your site
twitter_username: paulpadier
github_username:  magni-

# Build settings
markdown: kramdown
